import type { RolePermissionMap } from "./permission.types.js";
import { PERMISSIONS } from "./permissions.js";

const REQUESTER_PERMISSIONS = [
  PERMISSIONS.REQUEST_CREATE,
  PERMISSIONS.REQUEST_READ_OWN,
  PERMISSIONS.REQUEST_UPDATE_OWN,
  PERMISSIONS.REQUEST_SUBMIT,
  PERMISSIONS.REQUEST_CANCEL,
  PERMISSIONS.COMMENT_CREATE,
] as const;

export const ROLE_PERMISSIONS = {
  EMPLOYEE: [...REQUESTER_PERMISSIONS],
  MANAGER: [
    ...REQUESTER_PERMISSIONS,
    PERMISSIONS.REQUEST_READ_TEAM,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.ANALYTICS_TEAM,
  ],
  ADMIN: [
    ...REQUESTER_PERMISSIONS,
    PERMISSIONS.REQUEST_READ_TEAM,
    PERMISSIONS.REQUEST_READ_ALL,
    PERMISSIONS.REQUEST_DELETE,
    PERMISSIONS.REQUEST_APPROVE,
    PERMISSIONS.REQUEST_REJECT,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.USER_ROLE_UPDATE,
    PERMISSIONS.USER_STATUS_UPDATE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ANALYTICS_TEAM,
    PERMISSIONS.ANALYTICS_ORGANIZATION,
  ],
} as const satisfies RolePermissionMap;
